### ISSUE TITLE
nowe pole dla dokumentu sprzedazy c

### ISSUE THREAD

**Issue by mleplawy** [LukeOtdr/api-subiekt-gt#110]
chcialem dodac mozliwosc dodawania opisu do dokumentu sprzedazy np faktury Opisu dodalem do pliku order.php

> $selling_doc->Opis = "testowy opis";

ale zwraca mi blad 

"state": "fail", "message": "Unable to lookup `opis': Unknown name", "obj_dump": "APISubiektGT\\SubiektGT\\Order Object\n(\n [subiektGt:protec

czy powinienem cos jeszcze zdefiniowac najpierw? w dokumentacji sfery jest takie pole

**Comment by mleplawy** [comment]
racja w tej metodzie nie ma pola Opis jest za to Uwagi dziala do zamkniecia

**Comment by Lukegpl** [comment]
Dokładnie 😉

Pozdrawiam
Łukasz Golonka


W dniu śr., 6.03.2024 o 12:36 mleplawy ***@***.***>
napisał(a):
