### ISSUE TITLE
"Nie można zapisać dokumentu. Dane zostały zmienione w tle"  - przy próbie zapisu zamówienia do PAi/FV

### ISSUE THREAD

**Issue by holospl** [LukeOtdr/api-subiekt-gt#44]
Dzień dobry,
zapis do zamówienia przebiega w zasadzie bez problemu,
niestety ale próba zapisu/realizacji zamówienia do FV lub PA kończy się komunikatem
""state": "fail", "message": "Source: Subiekt.FV.1
Description: Nie można zapisać dokumentu. Dane zostały zmienione w tle.\"

Próbowałem zapisać nowe zamówienia, jak i jakieś stare niezrealizowane, jakieś pomysły?

**Comment by LukeOtdr** [comment]
Cześć,

no właśnie tak wyglądają wiele mówiące wyjątki z Subiekta. Pytanie czy to jest baza testowa i czy inni mają dostęp ? Typu stacje robocze itp ?

**Comment by holospl** [comment]
Baza jest "produkcyjna", jest podpiętych do niej kilka stanowisk roboczych. Prawdę mówiąc przejrzałem dokumentację i stwierdziłem - "kurcze, świetnie opisane i proste, nie będę się bawił w środowisko testowe, zajmie mi to kilka chwil". No i się przeliczyłem. Wyłączyłem przed chwilą wszystkie stacje robocze i niestety niczego to nie zmieniło. 

Jedyna wzmianka w google'ach to triggery w bazie, ale z tego co kojarzę to dorabiałem trigger lub dwa, nie operują one na dokumentach, dla pewności je zaraz wyłączę ale na 90% to nie to.

**Comment by holospl** [comment]
Faktycznie była to kwestia triggera. Dorabiałem kiedyś wyzwalacz rejestrujący godzinę dodania dokumentu, nie do końca rozumiem w czym ma problem, najważniejsze że po jego wyłączeniu zapisywanie dokumentu działa. Dzięki za zainteresowanie i chęć pomocy! :)
