### ISSUE TITLE
Dokument WZ

### ISSUE THREAD

**Issue by gajosadrian** [LukeOtdr/api-subiekt-gt#57]
Jest możliwość wystawienia dokumentu WZ? Czy jest możliwość dopisania tego modułu?

**Comment by LukeOtdr** [comment]
Możesz się wzorować na (zrobić idento):
https://github.com/LukeOtdr/api-subiekt-gt/blob/master/src/apisubiektgt/subiektgt/order.php

Z tym że w linii 253:

**$this->orderGt = $this->subiektGt->SuDokumentyManager->DodajZK();**

Dodasz sobie WZ. Pewnie w dokumentacji będzie DodajWZ();
Wywalisz metodę makeSale i zmienisz nazwy (metod, klasy, i przestrzeni nazw) z "order" na coś innego. I moim zdaniem powinno działać.
Dodawanie klienta masz, dodawanie pozycji również masz gotowe.
