### ISSUE TITLE
Edycja stanu towaru

### ISSUE THREAD

**Issue by gajosadrian** [LukeOtdr/api-subiekt-gt#58]
Jaki parametr edytuje stan towaru na magazynie? Nie mogę znaleźć w dokumentacji. Czy jest to "qty"? Dokumentacja chyba nie pełna.

**Comment by LukeOtdr** [comment]
Jeśli chodzi o "stan" produktu to nie edytujesz go wprost. Musisz stworzyć przyjęcie magazynowe na dany produkt (PZ). W subiekcie nie mam możliwości (przynajmniej ja na ten temat nic nie wiem) aby edytować stan produktu.
