### ISSUE TITLE
Wybór użytkownika

### ISSUE THREAD

**Issue by gajosadrian** [LukeOtdr/api-subiekt-gt#59]
Można zaktualizować lub podpowiedzieć w jaki sposób można zedytować kod i zdefiniować zapytanie, aby można było wybierać użytkownika subiekta, a nie działać na jednym użytkowniku z konfiguracji Parametrów uruchomieniowych?

**Comment by LukeOtdr** [comment]
Na jakim poziomie chciałbyś zmieniać użytkownika na jakim etapie ?

**Comment by gajosadrian** [comment]
Przy wystawianiu np. faktury, paragonu, aby był ślad który użytkownik to zrobił.
