### ISSUE TITLE
Nie łączy się z subiektem

### ISSUE THREAD

**Issue by G910** [LukeOtdr/api-subiekt-gt#66]
Cześć, podczas próby instalacji i przetestowania wyrzuca mi w okienku odpowiedzi serwera błąd:
```
Notice:  Trying to get property 'SuDokumentyManager' of non-object in C:\inetpub\wwwroot\api-subiekt-gt-master\src\apisubiektgt\subiektgt\document.php on line 37



Fatal error:  Uncaught Error: Call to a member function Istnieje() on null in C:\inetpub\wwwroot\api-subiekt-gt-master\src\apisubiektgt\subiektgt\document.php:37
Stack trace:
#0 C:\inetpub\wwwroot\api-subiekt-gt-master\public\api\index.php(77): APISubiektGT\SubiektGT\Document->__construct(NULL, Array)
#1 {main}
  thrown in C:\inetpub\wwwroot\api-subiekt-gt-master\src\apisubiektgt\subiektgt\document.php on line 37
```

**Comment by LukeOtdr** [comment]
Cześć,

na mój gust coś z tworzenie obiektów "Sfery" jest coś nie tak. Jeśli dostajesz pusty obiekt (null) Sferowy to sprawdzić trzeba czy ona jest aktywowana w subiekcie na maszynie na której próbujesz testować skrypty.

**Comment by G910** [comment]
Hej ponownie, cały myk polega na tym, że wszystko jest si ze Sferą, aktywowana itd.

**Comment by LukeOtdr** [comment]
Zrób prosty test - upewnij się że nie masz odpalonego subiekta na testowanej maszynie z win+subiekt. Jeśli masz to pozamykaj na windzie wszystkie procesy Subiekta z task managera. Jak to będziesz miał gotowe to odpal połączenie testowe z php-a i zobacz czy się pojawił w procesach windy "Subiekt".  Jeśli się pojawi proces subiekta tzn że php go uruchamia i trzeba szukać dalej. Jeśli go nie ma patrz moja wcześniejsza odpowiedź.
