### ISSUE TITLE
Wydruk paragonu do faktury

### ISSUE THREAD

**Issue by piotrzeranski** [LukeOtdr/api-subiekt-gt#74]
Cześć,
chciałbym zapytać się jak wystawić Fakturę z fiskalizacją ?
Chodzi mi o to że wystawiam fakturę na osobę fizyczną i muszę ją zafiskalizować na drukarce fiskalnej.
Wiem że drukuje dokument Faktura (z NIPem)/Paragon natomiast Faktura+paragon nie jest drukowany. Czy jest jakaś inna metoda która musi to wywołać?
dopisałem w order.php to zaraz po `$selling_doc->Zapisz();`
`$selling_doc->Drukuj();	`

**Comment by LukeOtdr** [comment]
Drukuj w jakim sensie ? Chcesz wysłać dokument na drukarkę lub drukarkę fiskalną ? Zastanawiam się czy jest możliwe przez PHP ;) ponieważ przy standardowym wywołaniu drukuj wyświetla się okno dialogwe z drukarkami i opcjami wydruku jak i fiskalizacją.  Generalnie odsyłam Cie do dokumentacji obiektowej Sfery tam znajdziesz wszystko. Wiem napewno, że możesz wystawić dokument sprzedaży na podstawie zamówienia lub WZ. Tak więc jeśli masz FV na osobę fizyczną możesz wystawić paragon na podstawie tego dokumentu. Zastanawiam czy nie łatwiej będzie (tak ja robię), że wystawiamy paragony imienne. Wystawiasz taki paragon na osobę fizyczną i musisz zafiskalizować. Klient zawsze może zrobić manewr, że chce FV na podmiot gospodarczy.

**Comment by paweleq1994** [comment]
po `$selling_doc->Zapisz();` trzeba dodać

```
$selling_doc->RejestrujNaUF = true;
$selling_doc->DrukarkaFiskalnaId = 12;
$selling_doc->Drukuj();
```
Drukuje wtedy jednocześnie z drukarki fiskalnej i zwykłej. Id drukarki fiskalnej jest w bazie w tabeli uf_Konfiguracja w kolumnie uko_Id

**Comment by LukeOtdr** [comment]
Dziś próbowałem testować rozwiązanie:

`
$selling_doc->RejestrujNaUF = true;
$selling_doc->DrukarkaFiskalnaId = 12;
$selling_doc->Drukuj();
`

w kontekście innej aplikacji webowej ale mi zwieszało aplikacji na uruchomieniu Drukuj(); 
Czy coś trzeba jeszcze ustawić domyślnie ? 
Pracowałem na fiskalizacji zdalnej.

**Comment by paweleq1994** [comment]
Miałem taki sam problem ze zwieszaniem się na Drukuj(); zanim jeszcze dodałem opcję wydruku na UF. Do teraz nie wiem dlaczego to nie działało ani dlaczego zaczęło to działać :D Jedyne co mogę zaproponować to drukowanie wg ustawień ale nie mam pewności czy to pomoże.

` $oUstWyd = $selling_doc->PodajUstawieniaDrukowania(Null);//null to domyslny wzorzec wydruku`
`$oUstWyd->DrukarkaDomyslSysOp = false;`
`$oUstWyd->Drukarka = $this->printer_name;`
`$oUstWyd->IloscKopii = $this->number_of_copies;`
`$selling_doc->DrukujWgUstawien($oUstWyd);`

**Comment by lukaszdela** [comment]
cześć,

temat został zamknięty ale chciałem się z Wami podzielić obserwacjami :)

```
$oUstWyd = $selling_doc->PodajUstawieniaDrukowania(Null);//null to domyslny wzorzec wydruku
$oUstWyd->DrukarkaDomyslSysOp = false;
$oUstWyd->Drukarka = $this->printer_name;
$oUstWyd->IloscKopii = $this->number_of_copies;
$selling_doc->DrukujWgUstawien($oUstWyd);
```
próbowałem podobnie określić parametry / ustawienia drukowania ale niestety w moim przypadku to nie zadziałało, teoretycznie powinno.

Generalnie kod  załatwia wydruk paragonu na drukarce fiskalnej
```
$selling_doc->RejestrujNaUF = true;
$selling_doc->DrukarkaFiskalnaId = 12;
$selling_doc->Drukuj();
```
zawias aplikacji na Drukuj() w moim przypadku wynikał z ustawienia domyślnego ustawienia wzorca wydruku dla paragonu
"Drukuj na domyślnej..." (screen) > systemowej instead określonej manualnie

![obraz](https://user-images.githubusercontent.com/39537338/172708375-c7e32a70-dac8-411e-8af7-0a540dd1db9c.png)

po określeniu drukarki, nawet dowolnej (eg. Fax) > w moim przypadku i tak drukuje tylko na drukarce fiskalnej > ilość kopii 0
nie ma problemu / zawiasu wydruku paragonu na DF

![obraz](https://user-images.githubusercontent.com/39537338/172709212-71f075e8-7453-467c-8370-9f0737179e03.png)
